# Generated by Django 4.2 on 2023-04-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_blogpost_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='topic',
        ),
        migrations.AddField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.blogpost'),
            preserve_default=False,
        ),
    ]
