# Generated by Django 4.1.5 on 2023-02-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_library_user_reader_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library_allowed_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.library_book')),
            ],
        ),
    ]
