# Generated by Django 4.1.5 on 2023-02-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_artccomment_libraryuserreaderhistory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artclikes',
            unique_together={('article', 'user')},
        ),
    ]
