# Generated by Django 4.1.5 on 2023-02-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_artclikes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='artccomment',
            name='parrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.artccomment'),
        ),
    ]
