# Generated by Django 4.1.5 on 2023-02-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myapp', '0013_artccomment_parrent_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artclikes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='artclikes',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artclikes',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='artclikes',
            name='article',
        ),
    ]
