# Generated by Django 4.1.5 on 2023-02-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_artclikes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcarticle',
            name='header',
            field=models.CharField(max_length=1000),
        ),
    ]
