# Generated by Django 4.1.5 on 2023-02-19 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_artcarticle_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artccomment',
            name='parrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parrents', to='myapp.artccomment'),
        ),
    ]
